"""create tables

Revision ID: b9f0663e3bc5
Revises: 
Create Date: 2024-02-25 20:53:51.362851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f0663e3bc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aima',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('aima_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['aima_id'], ['aima.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('aima_id', sa.String(length=50), nullable=False),
    sa.Column('article_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['aima_id'], ['aima.id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('statuses',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default='75101dd7-f24f-425f-856f-bc7834011deb', nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'RECEIVED', name='statusesenum'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statuses_subscription_id'), 'statuses', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statuses_subscription_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_table('subscriptions')
    op.drop_table('cities')
    op.drop_table('users')
    op.drop_table('articles')
    op.drop_table('aima')
    # ### end Alembic commands ###
